### ISSUE TITLE
Import reduction/oxidation potential from CSV

### ISSUE THREAD

**Issue by kkthek** [ComPlat/ChemistryKnowledgeBase#241]
Import data from column 7, line 11-12: reduction/oxidation potential. 
[VLL-327.2_bagit.edit.csv](https://github.com/user-attachments/files/16730961/VLL-327.2_bagit.edit.csv)
[VLL-327 test csv export.xlsx](https://github.com/user-attachments/files/16730962/VLL-327.test.csv.export.xlsx)

Questions:
* Victor said there can be several values for each. how do they appear in the Excel/CSV?
* How should the import be done? Via an import button in the form editor?

![mockup](https://github.com/user-attachments/assets/8c870a34-8b57-4f27-8af6-7fbb97723b82)

**Comment by victorlarignon** [comment]
I think we might have to use an import button as there could be several times the same molecule in the CV investigation. So the easiest would be to let the user choose where to upload the file. Same goes for the potentials, excepted if that can be added to the ELN export files, otherwise we can't know what potentials are red/ox, so again, we might just let the user choose.

**Comment by kkthek** [comment]
I will extend the functionality:
* there will be multiple values (line 9-end, column 7) imported
* They will be imported in both fields (reduction/oxidation). The user will then just delete those which are incorrect.
* The dialog for editing is opened automatically after import.
* If technically feasible, I will add drag&drop for values (hint: https://jqueryui.com/droppable/#accepted-elements)

**Comment by kkthek** [comment]
Implemented 1-3. All values are imported to both fields. User can then delete values which are wrong and re-arrange them.

Drag&Drop between the 2 fields is difficult to implement. I skipped this.

**Comment by victorlarignon** [comment]
Hey, I reopened the import issue because I have a last query. The import works very well, thanks!
Would it be possible to round the numbers? Currently all the decimals are showing and it's really not necessary. Can you round it 2 numbers after the coma (i.e. -1.59 and 0.97 in this example, to the closest 100th)?

![image](https://github.com/user-attachments/assets/09042e27-b1b8-409a-9fe7-39836060a68a)

**Comment by kkthek** [comment]
done. values are round to 2 digits
